### ISSUE TITLE
Add credentials to person

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#83]
https://github.com/metanorma/metanorma-nist/issues/277 depends on Relaton recognising `credential` in the following grammar:

````
person = 
  element person {
    fullname?, credential*, affiliation*, person-identifier*, contact*
}

credential = element credential { text }
````

As far as I can see, it isn't recognised.

**Comment by opoudjis** [comment]
In addition, we have the convention in hashes that we supply the `content` node for a string:

`a.is_a?(String) ? FormattedString.new(content: a) : a`

Please extend that to affiliation_hash_to_bib:

`name = LocalizedString.new(a[:name][:content], a[:name][:language], a[:name][:script]) if a[:name]`

should be

````
if a[:name]
  name = a[:name].is_a?(String) ? FormattedString.new(content: a[:name]) : a
end
````

so that I can specify in hash:

````
  person:
    name:
      completename: Fred Flintstone
    affiliation:
    - name: Vice President, Medical Devices Quality & Compliance -- Strategic programmes
````

instead of

````
  person:
    name:
      completename: Fred Flintstone
    affiliation:
    - name: 
        content: Vice President, Medical Devices Quality & Compliance -- Strategic programmes
````
