### ISSUE TITLE
Add logo to organisations

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bib#85]
Another recent addition to the grammar which will be needed to read contributor metadata from YAML, per https://github.com/metanorma/metanorma-nist/issues/277:

````
organization =
  element organization {
    orgname+, subdivision*, abbreviation?, uri*, org-identifier*, contact*, logo?
}

logo = element logo { image }
````

`image` is defined in Metanorma; I would expect any hash to contain the `image/@src` attribute, and render it into XML as `<image src="{...}"/>`. So:

````
contributor:
  person: 
    completename: Fred Flintstone
  affiliation:
    name: Chief Technical Officer
    organization:
      name: International Organization for Standardization
      contact:
        - uri: https://www.iso.org
      logo: iso.gif
````

rendered as:

````
<contributor>
   <role type="author"/>
   <name>
     <completename>Fred Flintstone</completename>
   </name>
   <affiliation>
     <name>Chief Technical Officer</name>
     <organization>
       <name>International Organization for Standardization</name>
       <uri>https://www.iso.org</uri>
       <logo><image src="iso.gif"/></logo>
     </organization>
   </affiliation>
 </contributor>
````
